package io.github.nicheengine.aerial.enums.wayline;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.nichetoolkit.rest.RestKey;
import io.github.nichetoolkit.rest.util.I18nUtils;
import lombok.Getter;

import java.util.Optional;

@Getter
public enum ExecutionStep implements RestKey<Integer> {

    EXECUTION_STEP_INITIAL(0),

    EXECUTION_STEP_PRE_CHECK(1),

    EXECUTION_STEP_CHECK_WORK_MODE(2),

    EXECUTION_STEP_CHECK_EXECUTION(3),

    EXECUTION_STEP_CHECK_RETURN(4),

    EXECUTION_STEP_PREPARATION(5),

    EXECUTION_STEP_OPERATIONAL(6),

    EXECUTION_STEP_OPEN_COVER_PREPARATION(7),

    EXECUTION_STEP_WAITING_FOR_FLIGHT_SYSTEM_READINESS(8),

    EXECUTION_STEP_WAITING_FOR_RTK(9),

    EXECUTION_STEP_CHECK_RTK_SOURCE(10),

    EXECUTION_STEP_WAITING_FOR_FLIGHT_CONTROL(11),

    EXECUTION_STEP_WRESTING_FLIGHT_CONTROL(12),

    EXECUTION_STEP_GET_KMZ(13),

    EXECUTION_STEP_DOWNLOAD_KMZ(14),

    EXECUTION_STEP_KMZ_UPLOADING(15),

    EXECUTION_STEP_DYE_CONFIGURATION(16),

    EXECUTION_STEP_SET_DRONE_PARAMETER(17),

    EXECUTION_STEP_SET_TAKEOFF_PARAMETER(18),

    EXECUTION_STEP_SET_HOME_POINT(19),

    EXECUTION_STEP_WAYLINE_EXECUTION(20),

    EXECUTION_STEP_IN_PROGRESS(21),

    EXECUTION_STEP_RETURN_CHECK_PREPARATION(22),

    EXECUTION_STEP_LADING(23),

    EXECUTION_STEP_CLOSE_COVER(24),

    EXECUTION_STEP_EXIT_WORK_MODE(25),

    EXECUTION_STEP_DRONE_ABNORMAL_RECOVERY(26),

    EXECUTION_STEP_UPLOADING_FLIGHT_SYSTEM_LOGS(27),

    EXECUTION_STEP_CHECK_RECORDING_STATUS(28),

    EXECUTION_STEP_GET_MEDIA_FILES(29),

    EXECUTION_STEP_DOCK_ABNORMAL_RECOVERY(30),

    EXECUTION_STEP_NOTIFY_TASK_RESULTS(31),

    EXECUTION_STEP_TASK_COMPLETED(32),

    EXECUTION_STEP_RETRIEVAL_DRONE_LOG_LIST(33),

    EXECUTION_STEP_RETRIEVAL_DOCK_LOG_LIST(34),

    EXECUTION_STEP_UPLOAD_LOG_LIST_RESULTS(35),

    EXECUTION_STEP_RETRIEVAL_DRONE_LOG(36),

    EXECUTION_STEP_RETRIEVAL_DOCK_LOG(37),

    EXECUTION_STEP_COMPRESS_DRONE_LOG(38),

    EXECUTION_STEP_COMPRESS_DOCK_LOG(39),

    EXECUTION_STEP_UPLOAD_DRONE_LOG(40),

    EXECUTION_STEP_UPLOAD_DOCK_LOG(41),

    EXECUTION_STEP_NOTIFY_LOG_RESULTS(42),

    EXECUTION_STEP_WAITING_FOR_SERVICE_RESPONSE(65533),

    EXECUTION_STEP_NO_SPECIFIC_STATUS(65534),

    EXECUTION_STEP_UNKNOWN(-1),
    ;

    private final Integer step;

    private final String message;

    ExecutionStep(Integer step) {
        this.step = step;
        this.message = I18nUtils.message(name());
    }

    @JsonValue
    @Override
    public Integer getKey() {
        return this.step;
    }

    @JsonCreator
    public static ExecutionStep parseKey(Integer key) {
        ExecutionStep parsedKey = RestKey.parseKey(ExecutionStep.class, key);
        return Optional.ofNullable(parsedKey).orElse(ExecutionStep.EXECUTION_STEP_UNKNOWN);
    }
}
