package io.github.nicheengine.aerial.enums.wayline;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.nichetoolkit.rest.RestKey;
import io.github.nichetoolkit.rest.util.I18nUtils;
import lombok.Getter;

import java.util.Optional;

@Getter
public enum FlighttaskBreakReason implements RestKey<Integer> {

    FLIGHT_TASK_NORMAL(0),

    FLIGHT_TASK_NOT_ID(1),

    FLIGHT_TASK_UNCOMMON_ERROR(2),

    FLIGHT_TASK_ERROR_LOADING_FILE(4),

    FLIGHT_TASK_ERROR_BREAKPOINT_FILE(5),

    FLIGHT_TASK_INCORRECT_PARAMETER(6),

    FLIGHT_TASK_PARSING_FILE_TIMEOUT(7),

    FLIGHT_TASK_ALREADY_STARTED(257),

    FLIGHT_TASK_UNABLE_TO_INTERRUPT_WAYLINE(258),

    FLIGHT_TASK_NOT_STARTED(259),

    FLIGHT_TASK_FLIGHT_TASK_CONFLICT(261),

    FLIGHT_TASK_UNABLE_TO_RESUME_WAYLINE(262),

    FLIGHT_TASK_MAXIMUM_ALTITUDE_LIMIT(513),

    FLIGHT_TASK_MAXIMUM_DISTANCE_LIMIT(514),

    FLIGHT_TASK_TOO_LOW_HEIGHT(516),

    FLIGHT_TASK_OBSTACLE_AVOIDANCE(517),

    FLIGHT_TASK_POOR_RTK(518),

    FLIGHT_TASK_BOUNDARY_OF_RESTRICTED_ZONE(519),

    FLIGHT_TASK_GEO_ALTITUDE_LIMIT(521),

    FLIGHT_TASK_TAKEOFF_REQUEST_FAILED(522),

    FLIGHT_TASK_TAKEOFF_EXECUTION_FAILED(523),

    FLIGHT_TASK_WAYLINE_TASK_REQUEST_FAILED(524),

    FLIGHT_TASK_RTK_FIXING_REQUEST_FAILED(526),

    FLIGHT_TASK_RTK_FIXING_EXECUTION_FAILED(527),

    FLIGHT_TASK_WEAK_GPS(769),

    FLIGHT_TASK_ERROR_RC_MODE(770),

    FLIGHT_TASK_HOME_POINT_NOT_REFRESHED(771),

    FLIGHT_TASK_LOW_BATTERY(772),

    FLIGHT_TASK_LOW_BATTERY_RTH(773),

    FLIGHT_TASK_RC_DISCONNECTION(775),

    FLIGHT_TASK_ON_THE_GROUND(778),

    FLIGHT_TASK_ABNORMAL_VISUAL_STATUS(779),

    FLIGHT_TASK_INVALID_ALTITUDE(780),

    FLIGHT_TASK_CALCULATION_ERROR(781),

    FLIGHT_TASK_STRONG_WINDS_RTH(784),

    FLIGHT_TASK_USER_EXIT(1281),

    FLIGHT_TASK_USER_INTERRUPTION(1282),

    FLIGHT_TASK_USER_TRIGGERED_RTH(1283),

    FLIGHT_TASK_INCORRECT_START_INFORMATION(1539),

    FLIGHT_TASK_UNSUPPORTED_COORDINATE_SYSTEM(1540),

    FLIGHT_TASK_UNSUPPORTED_ALTITUDE_MODE(1541),

    FLIGHT_TASK_UNSUPPORTED_TRANSITIONAL_WAYLINE_MODE(1542),

    FLIGHT_TASK_UNSUPPORTED_YAW_MODE(1543),

    FLIGHT_TASK_UNSUPPORTED_YAW_DIRECTION_REVERSAL_MODE(1544),

    FLIGHT_TASK_UNSUPPORTED_WAYPOINT_TYPE(1545),

    FLIGHT_TASK_INVALID_COORDINATED_TURNING_TYPE(1546),

    FLIGHT_TASK_INVALID_GLOBAL_SPEED(1547),

    FLIGHT_TASK_WAYPOINT_NUMBER_ABNORMAL(1548),

    FLIGHT_TASK_INVALID_LATITUDE_AND_LONGITUDE(1549),

    FLIGHT_TASK_ABNORMAL_TURNING_INTERCEPT(1550),

    FLIGHT_TASK_INVALID_SEGMENT_MAXIMUM_SPEED(1551),

    FLIGHT_TASK_INVALID_TARGET_SPEED(1552),

    FLIGHT_TASK_INVALID_YAW_ANGLE(1553),

    FLIGHT_TASK_BREAKPOINT_INVALID_TASK_ID(1555),

    FLIGHT_TASK_BREAKPOINT_INVALID_PROGRESS_INFORMATION(1556),

    FLIGHT_TASK_BREAKPOINT_ERROR_TASK_STATE(1557),

    FLIGHT_TASK_BREAKPOINT_INVALID_INDEX_INFORMATION(1558),

    FLIGHT_TASK_BREAKPOINT_INCORRECT_LATITUDE_AND_LONGITUDE(1559),

    FLIGHT_TASK_BREAKPOINT_INVALID_YAW(1560),

    FLIGHT_TASK_BREAKPOINT_INCORRECT_FLAG_SETTING(1561),

    FLIGHT_TASK_WAYLINE_GENERATION_FAILED(1563),

    FLIGHT_TASK_WAYLINE_EXECUTION_FAILED(1564),

    FLIGHT_TASK_WAYLINE_OBSTACLE_SENSING(1565),

    FLIGHT_TASK_UNRECOGNIZED_ACTION_TYPE(1588),

    FLIGHT_TASK_DUPLICATE_ACTION_ID(1595),

    FLIGHT_TASK_ACTION_ID_NOT_65535(1598),

    FLIGHT_TASK_INVALID_NUMBER_OF_ACTION_GROUPS(1602),

    FLIGHT_TASK_ERROR_EFFECTIVE_RANGE(1603),

    FLIGHT_TASK_BREAKPOINT_INVALID_ACTION_INDEX(1606),

    FLIGHT_TASK_BREAKPOINT_TRIGGER_RUNNING_ABNORMAL(1608),

    FLIGHT_TASK_BREAKPOINT_DUPLICATE_ACTION_GROUP_ID(1609),

    FLIGHT_TASK_BREAKPOINT_DUPLICATE_ACTION_GROUP_POSITION(1610),

    FLIGHT_TASK_BREAKPOINT_INVALID_ACTION_GROUP_POSITION(1611),

    FLIGHT_TASK_BREAKPOINT_INVALID_ACTION_ID(1612),

    FLIGHT_TASK_BREAKPOINT_UNABLE_TO_INTERRUPT(1613),

    FLIGHT_TASK_INCORRECT_BREAKPOINT_INFORMATION(1614),

    FLIGHT_TASK_BREAKPOINT_UNRECOGNIZED_ACTION_TYPE(1634),

    FLIGHT_TASK_BREAKPOINT_UNRECOGNIZED_TRIGGER_TYPE(1649),

    FLIGHT_TASK_UNKNOWN(-1),
    ;

    private final Integer reason;

    private final String message;

    FlighttaskBreakReason(Integer reason) {
        this.reason = reason;
        this.message = I18nUtils.message(name());
    }

    @JsonValue
    @Override
    public Integer getKey() {
        return this.reason;
    }

    @JsonCreator
    public static FlighttaskBreakReason parseKey(Integer key) {
        FlighttaskBreakReason parsedKey = RestKey.parseKey(FlighttaskBreakReason.class, key);
        return Optional.ofNullable(parsedKey).orElse(FlighttaskBreakReason.FLIGHT_TASK_UNKNOWN);
    }
}
