server.port=8080

spring.jmx.enabled=false
spring.application.name=aerial-engine-server
spring.jmx.default-domain=aerial-engine-server

server.servlet.context-path=/aerial

server.tomcat.connection-timeout=600s
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=servlet

spring.jackson.default-property-inclusion=non_null
spring.jackson.parser.allow-unquoted-control-chars=true
spring.jackson.parser.allow-comments=true
spring.jackson.parser.allow-single-quotes=true
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.time-zone=GMT+8

spring.main.allow-circular-references =true
mybatis.configuration.map-underscore-to-camel-case=true

# console log error configuration
nichetoolkit.rest.error.console-log.rest-exception-enabled=false
nichetoolkit.rest.error.console-log.common-exception-enabled=true

# jwt worker configuration
nichetoolkit.rest.jwt.enabled=true
nichetoolkit.rest.jwt.algorithm=hs256
nichetoolkit.rest.jwt.secret=ICBwpv3gDQLfdrtTuek5wtQ
nichetoolkit.rest.jwt.kid=
nichetoolkit.rest.jwt.issuer=io.github.nicheengine
nichetoolkit.rest.jwt.audiences=
nichetoolkit.rest.jwt.expire-time=0
nichetoolkit.rest.jwt.expire-unit=millis
nichetoolkit.rest.jwt.issued-delay-time=0
nichetoolkit.rest.jwt.issued-delay-unit=millis
nichetoolkit.rest.jwt.not-before-enabled=false


# sha worker configuration
# app: ICBwpv3gDQLfdrtTuek5wtQ
nichetoolkit.rest.sha.enabled=true
nichetoolkit.rest.sha.algorithm=sha256
nichetoolkit.rest.sha.secret=ZbqWif8ZSnjWQS5iznqXcUoKEjAV4sqJVLtV2XoeUDkGe3vPe8mAL3PhdulCRaPQxI46V86kzmf97UeigGk

# identity worker configuration
nichetoolkit.rest.identity.enabled=true
nichetoolkit.rest.identity.type=config
nichetoolkit.rest.identity.config.worker-id=1
nichetoolkit.rest.identity.config.center-id=2

# intercept configuration
nichetoolkit.rest.intercept.enabled=true
nichetoolkit.rest.intercept.logging-enabled=false
nichetoolkit.rest.intercept.userlog-enabled=true
nichetoolkit.rest.intercept.bean-enabled=true
nichetoolkit.rest.intercept.body-length=1024
nichetoolkit.rest.intercept.error-length=1024
nichetoolkit.rest.intercept.message-length=1024
nichetoolkit.rest.intercept.result-length=1024

# http client configuration
nichetoolkit.rest.http.enabled=true
nichetoolkit.rest.http.connect-timeout=2000
nichetoolkit.rest.http.read-timeout=30000
nichetoolkit.rest.http.request-timeout=200
nichetoolkit.rest.http.max-core-size=5
nichetoolkit.rest.http.max-idle-size=10
nichetoolkit.rest.http.http-type=ok_http_client
nichetoolkit.rest.http.charset=utf-8
nichetoolkit.rest.http.encoding-mode=none
nichetoolkit.rest.http.retry-times=0
nichetoolkit.rest.http.keep-alive-time=600000
nichetoolkit.rest.http.proxy.type=socks
nichetoolkit.rest.http.proxy.hostname=
nichetoolkit.rest.http.proxy.port=


nichetoolkit.rest.i18n.enabled=true
nichetoolkit.rest.i18n.locale=china
nichetoolkit.rest.i18n.basename=
nichetoolkit.rest.i18n.session-resolver-enabled=false
nichetoolkit.rest.i18n.cookie-resolver-enabled=false
nichetoolkit.rest.i18n.interceptor-enabled=true
nichetoolkit.rest.i18n.param-name=lang

# logback configuration
nichetoolkit.rest.logback.enabled=true
nichetoolkit.rest.logback.logging-key=loggingKey
nichetoolkit.rest.logback.attributes=_t
nichetoolkit.rest.logback.request-key=requestKey
nichetoolkit.rest.logback.request-header=X-Request-ID
nichetoolkit.rest.logback.argument-length=1024
nichetoolkit.rest.logback.prefix-length=12

# service configuration
nichetoolkit.rice.service.unique-model=false
nichetoolkit.rice.service.identity-invade=false
nichetoolkit.rice.service.identity-check=false
nichetoolkit.rice.service.unique-name=true
nichetoolkit.rice.service.nonnull-name=true
nichetoolkit.rice.service.partition.query-size=2000
nichetoolkit.rice.service.partition.save-size=500
nichetoolkit.rice.service.partition.delete-size=1000
nichetoolkit.rice.service.before-skip=true
nichetoolkit.rice.service.after-skip=true
nichetoolkit.rice.service.save-result-ignored=true

# login configuration
nichetoolkit.rice.login.enabled=true
nichetoolkit.rice.login.token-prefixes=Bearer
nichetoolkit.rice.login.skip-urls=/docs/**
nichetoolkit.rice.login.token-headers=Authorization
nichetoolkit.rice.login.token-expiration=1800
nichetoolkit.rice.login.token-time-unit=seconds
nichetoolkit.rice.login.access-token-header=Access-Token
nichetoolkit.rice.login.access-auth-header=Access-Auth

# hikari datasource configuration
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# service configuration
nichetoolkit.rice.service.delete-mode=remove
nichetoolkit.rice.service.delete.logic-mode=config
nichetoolkit.rice.service.delete.config-mark=number
nichetoolkit.rice.service.delete.auto-mark=identity
nichetoolkit.rice.service.delete.accurate-judge=true
nichetoolkit.rice.service.dynamic-table=false

# postgresql table configuration
nichetoolkit.mybatis.table.use-logic=true
nichetoolkit.mybatis.table.use-operate=false
nichetoolkit.mybatis.table.update-logic=false
nichetoolkit.mybatis.table.exclude-unused=true
nichetoolkit.mybatis.table.sql-script-show=true
nichetoolkit.mybatis.table.mysql-ignore-insert=false
nichetoolkit.mybatis.table.datetime-now=now()
nichetoolkit.mybatis.table.database-type=postgresql
nichetoolkit.mybatis.table.style-type=lower_underline
nichetoolkit.mybatis.table.excluded-type=excluded

nicheengine.aerial.websocket.endpoints=/api/v1/ws
nicheengine.aerial.websocket.allowed-origins=*
nicheengine.aerial.mqtt.topics=sys/product/+/status,thing/product/+/requests

logging.config=classpath:logback-spring.xml
logging.file.path=logs

spring.profiles.active=dev

#SpringDoc的API包扫描路径，如果不配置，SpringDoc 自动扫描整个项目类路径，它会自动识别所有 @RestController、@RequestMapping 等注解，生成 API 文档
springdoc.packages-to-scan=io.github.nicheengine.aerial.controller
# 是否开启swagger界面，依赖OpenApi，默认为true，如果要开启需要OpenApi同时开启
springdoc.swagger-ui.enabled=true
# 内置 Swagger UI 的访问路径，默认值为/swagger-ui/index.html
springdoc.swagger-ui.path=/docs/swagger-ui/index.html
#指定OpenAPI文档的URL（注意这里一定要与api-docs.path保持一致，否则会请求失败）
springdoc.swagger-ui.url=/docs/v3/api-docs
#是否禁用Swagger UI自带的示例接口（如 Petstore 等默认接口），默认值为false，仅展示当前项目的 API
springdoc.swagger-ui.disable-swagger-default-url=false
#是否启用OpenAPI文档端点，默认为true
springdoc.api-docs.enabled=true
#OpenAPI 3规范的文档访问路径，默认值为/v3/api-docs
springdoc.api-docs.path=/docs/v3/api-docs
